# Generated by Django 4.1.5 on 2023-02-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_country_alter_address_options_book_published_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_country',
            new_name='published_countries',
        ),
    ]
